### ISSUE TITLE
Problems with installation

### ISSUE THREAD

**Issue by yonatanbitton** [bmcinnes/UMLS-Interface#1]
Hello. I've opened StackOverflow post for this issue: 
https://stackoverflow.com/questions/57641155/using-ulmssimilarity-perl-access-denied-for-mysql-user

I'm getting a simple error but I don't know how to solve it.

While performing make test on this perl package (Linux) https://metacpan.org/pod/UMLS::Interface:
`DBI connect('umls;mysql_read_default_group=client;','',...) failed: Access denied for user 'jon'@'localhost' (using password: NO) at /home/jon/UMLS/UMLS-Interface-1.51/blib/lib/UMLS/Interface/CuiFinder.pm line 2465.
`
I have a password, but I don't know how can I supply it during the installation.

My desire is to make the tests & installation work for both the UMLS Interface/similarity in order to find similarity & relatedness between words. If there exists some web-server that I can query for similarity, it might be a good detour.

# Tries:
Trying to install with cpanm

`(base) jon@jon:~/UMLS/UMLS-Interface-1.51$ sudo cpanm UMLS::Interface UMLS::Interface is up to date. (1.51)
`
Here it looks installed ok, but then I have the same problem with UMLS-SIMILARITY on the make test.

2. Trying to install with :

`perl Makefile.PL make make test make install`

Output:
```
(base) jon@jon:~/UMLS/UMLS-Interface-1.51$ perl Makefile.PL
Checking if your kit is complete...
Warning: the following files are missing in your kit:
    t/mysql.t
Please inform the author.
Generating a Unix-style Makefile
Writing Makefile for UMLS::Interface
Writing MYMETA.yml and MYMETA.json

```

And then on the '`make test`' I get the database error

`(Access denied for user 'jon'@'localhost' (using password: NO)
`

3. I've searched where I can supply config file / mysql password in UMLS-Interface or UMLS-Similarity packages. Didn't find.

4. I've tried to install DBI & DBD in several methods, all routes gets me to the same error.

5. I've tried the web-interface: https://metacpan.org/pod/distribution/UMLS-Similarity/utils/query-umls-similarity-webinterface.pl But get the following error:
`
(base) jon@jon:~/UMLS/UMLS-Similarity-1.47/utils$ query-umls-similarity-webinterface.pl hand skull Default Settings: --default http://atlas.ahc.umn.edu/ --measure path --sab MSH --rel PAR/CHD User Settings: No user defined settings
`
`
500 Can't connect to atlas.ahc.umn.edu:80http://atlas.ahc.umn.edu//cgi-bin/umls_similarity.cgi?word1=hand&word2=skull&sab=MSH&rel=PAR%2FCHD&similarity=path&button=Compute+Similarity&sabdef=UMLS_ALL&reldef=CUI%2FPAR%2FCHD%2FRB%2FRN&relatedness=vector <>()<>() ^C
`

6. I tried on Windows as well.

`DBI connect('umls;mysql_read_default_group=client;','',...) failed: Can't connect to MySQL server on 'localhost' (10061) at E:\umls_perl\UMLS-Interface-1.51\blib\lib/UMLS/Interface/CuiFinder.pm line 2465
`
How can I solve it? 

I'm willing to try any solution.
Does maybe someone have a paid service in order to do it? 
Maybe connecting to a remote VM with everything installed where I can use the package ?
Maybe someone have a python version for it or in another language ?

Thanks

**Comment by yonatanbitton** [comment]
I've solved it on Windows, just tried to install everything again with Mysql 5.5, including installing all of the prerequisites for UMLS-Interface and it worked. Thanks

**Comment by dianizzah** [comment]
Hello, i got similar problem on windows using MySQL 8.0.37 and Strawberry Perl 5.36.1.1. the UMLS::interface won't connect to  DBI as it shows `'DBI connect('umls;mysql_read_default_group=client;','',...) failed: Access denied for user 'ODBC'@'localhost' (using password: NO) at D:\apps\Strawberry\cpan\build\UMLS-Interface-1.51-0\blib\lib/UMLS/Interface/CuiFinder.pm line 2465.#Can't call method "err" on an undefined value at D:\apps\Strawberry\cpan\build\UMLS-Interface-1.51-0\blib\lib/UMLS/Interface/ErrorHandler.pm line 113.`
should i get MySQL 5.5? but when i tried using that sql version, the DBD::mysql works only mySQL 8.xx version
